# Nominate a PyTorch Ambassador

**Description:** Submit a nomination for the PyTorch Ambassador Program.

**Title Template:** [Nomination] <Nominee Name>

**Labels:** nomination, pending-review, ambassador

---

> 📝 **Note:** Please fill out the above field with the name of your nominee replacing `<Nominee Name>`.

# 🎖 PyTorch Ambassador Nomination Request

Thank you for your interest in the **PyTorch Ambassador Program**!  
Before submitting a nomination, please ensure you have **read the** [PyTorch Ambassador Program Requirements](https://github.com/pytorch-fdn/ambassador-program/blob/main/README.md)  
and that the nominee meets the eligibility criteria outlined below.

## ✅ Are You Nominating Yourself or Someone Else?

- [ ] I am **nominating myself** for the PyTorch Ambassador Program.  
- [ ] I am **nominating someone else** to become a PyTorch Ambassador.

## ✅ Pre-Submission Checklist

Please confirm that the nominee meets the following requirements:

- [ ] The nominee is **18 years of age or older**.  
- [ ] The nominee **agrees to abide by the [PyTorch Code of Conduct](https://github.com/pytorch-fdn/Foundation/blob/main/PyTorch%20Foundation%20Code%20of%20Conduct.md)**.  
- [ ] The nominee **agrees to comply with the [Linux Foundation Antitrust Policy](https://www.linuxfoundation.org/legal/antitrust-policy)**.  
- [ ] The nominee meets **at least one** of the qualifications listed in the [PyTorch Ambassador Program Requirements](https://github.com/pytorch-fdn/ambassador-program/blob/main/README.md).

## 📞 Contact Information

**Nominee Name:**  
**Nominee Email:**  
**Nominee's GitHub or GitLab Handle:**  
**Organization / Affiliation (Optional):**  
**City, State/Province, Country:**  

### **Nominator Information (If Different from Nominee)**

**Your Name:**  
**Your Email (Optional):**

## 🔹 Nominee’s Contributions to PyTorch

How has the nominee contributed to PyTorch?

- [ ] An active contributor to PyTorch repositories (e.g., commits, PRs, discussions).  
- [ ] A speaker at PyTorch events or workshops.  
- [ ] A PyTorch user group organizer or meetup host.  
- [ ] A researcher or educator using PyTorch in academic work or training.  
- [ ] An active leader in the PyTorch community with **at least one year** of experience in:  
  - [ ] Organizing events (virtual/in-person).  
  - [ ] Speaking at AI/ML conferences.  
  - [ ] Mentoring others in PyTorch.  
  - [ ] Creating technical content (e.g., blogs, videos, tutorials).

## 🏆 How Would the Nominee Contribute as an Ambassador?

_Explain how the nominee would engage with the PyTorch community, help the initiative thrive, and their plans for hosting events, mentoring, or knowledge-sharing._

## 🔗 Additional Information (Optional)

_Any extra information about the nominee or links to their work (blogs, conference talks, educational resources, etc.)._

---

## 🗳️ Next Steps

Once you submit this nomination, you will receive an **automatic comment with next steps**.  
A team member will review your submission and update the status accordingly.

**📌 Track the status of your nomination:**  
Labels may include:  
- `pending-review` → Your nomination is waiting for review  
- `needs-more-info` → Additional details are required  
- `approved` → Your nomination has been accepted  
- `rejected` → Your nomination was not approved  

**💬 Have Questions?**  
Submit a [Feedback Issue](https://github.com/pytorch-fdn/foundation-initiative/issues/new?template=feedback.yml)
