
name: "Acknowledge Reviewer Score"
on:
  issue_comment:
    types: [created]

jobs:
  acknowledge-score:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Respond to Score Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const comment = context.payload.comment;
            const commenter = comment.user.login;
            const body = comment.body.trim().toLowerCase();

            const scoreRegex = /^score:\s*(\d)/i;
            const match = comment.body.match(scoreRegex);

            if (match) {
              const score = parseInt(match[1]);
              if (score >= 1 && score <= 5) {
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number,
                  body: `📝 **Score received from @${commenter}: ${score}**\n⏳ Final decision will be calculated and posted after all reviewers have submitted their scores or in approximately 2 hours.`
                });
              } else {
                console.log("Invalid score value.");
              }
            } else {
              console.log("No score found in comment.");
            }
