name: "Mark Nomination as Under Review"
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: "The issue number of the nomination to update"
        required: true

jobs:
  update-nomination-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set issue status to under-review and scoring-in-progress
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = parseInt('${{ github.event.inputs.issue_number }}', 10);
            const { repo, owner } = context.repo;

            const issue = await github.rest.issues.get({
              owner,
              repo,
              issue_number
            });

            let labels = issue.data.labels.map(label => label.name);

            // Remove 'pending-review' if it's there
            labels = labels.filter(label => label !== "pending-review");

            // Add new labels if not already present
            if (!labels.includes("under-review")) labels.push("under-review");
            if (!labels.includes("scoring-in-progress")) labels.push("scoring-in-progress");

            await github.rest.issues.update({
              owner,
              repo,
              issue_number,
              labels
            });

            console.log(`Updated issue #${issue_number}: added 'under-review' and 'scoring-in-progress', removed 'pending-review' if present.`);
